# Site settings
title: CFD Simulation Hub
email: your-email@example.com
description: >-
  Advanced CFD simulation techniques, tutorials, and problem-solving strategies.
  Learn computational fluid dynamics from fundamentals to advanced applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://your-username.github.io" # the base hostname & protocol for your site
twitter_username: your_twitter
github_username: your_github

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  tutorials:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "CFD Expert"
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "tutorial"

# Pagination
paginate: 5
paginate_path: "/page:num/"

# SEO
author:
  name: CFD Expert
  email: your-email@example.com
  twitter: your_twitter

# Social
social:
  name: CFD Simulation Hub
  links:
    - https://twitter.com/your_twitter
    - https://github.com/your_github
    - https://linkedin.com/in/your_linkedin

