# Site settings
title: Auto Publisher Blog
email: your-email@example.com
description: >-
  A Jekyll blog with automated cross-platform publishing to LinkedIn, Medium, Reddit, and X (Twitter).
  Write once, publish everywhere automatically.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - .github/

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Auto Publisher"
      show_excerpts: true

# Social media settings for automation
social:
  linkedin:
    enabled: true
    company_page: false # set to true if posting to company page
  medium:
    enabled: true
    publication: "" # leave empty for personal account
  reddit:
    enabled: true
    subreddit: "programming" # default subreddit
  twitter:
    enabled: true
    include_hashtags: true

# Automation settings
automation:
  delay_minutes: 5 # delay between posts to different platforms
  include_excerpt: true
  max_excerpt_length: 280
  add_source_link: true

